name: build & gh-pages deployment & npm publish

# trigger rebuild: 4
on: push

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install, build & test
        run: |
          yarn install --frozen-lockfile
          yarn test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_RELEASE_GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          # PACKAGE_VERSION=$(node -e "console.log(require('./package.json').version)")
          echo "registry=https://registry.npmjs.org/" > ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" >> ~/.npmrc
          npm publish --tag=workflow-debug

  deploy-website:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install, build & prepare
        run: |
          yarn install --frozen-lockfile
          cd gallery
          yarn --frozen-lockfile
          yarn build
          echo 'ui.aragon.org' > dist/CNAME
          cp public/favicon.svg dist
      - name: Push to gh-pages
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.GH_PAGES_ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./gallery/dist
        uses: peaceiris/actions-gh-pages@v2
